name             'rabbitmq-in-depth'
maintainer       'Gavin M. Roy'
maintainer_email 'gavinmroy@gmail.com'
license          'BSD'
description      'Additional setup work for RabbitMQ in Depth Vagrant File'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'apt'
depends          'chef-cookbook-ssl'
depends          'git'
depends          'python'
depends          'rabbitmq'
depends          'supervisor'
depends          'zeromq'