# -*- mode: ruby -*-
# vi: set ft=ruby :
rabbitmq_version = '3.2.3'

Vagrant.configure("2") do |config|
  config.vm.box_url = "http://gavinroy.com/downloads/rabbitmq-in-depth/saucy-server.box"
  config.vm.box = "rabbitmq-in-depth"

  config.vm.define "primary", primary: true do |primary|
    primary.vm.hostname = 'primary'
    primary.vm.network :forwarded_port, guest: 1883, host: 1883
    primary.vm.network :forwarded_port, guest: 5671, host: 5671
    primary.vm.network :forwarded_port, guest: 5672, host: 5672
    primary.vm.network :forwarded_port, guest: 8883, host: 8883
    primary.vm.network :forwarded_port, guest: 8888, host: 8888
    primary.vm.network :forwarded_port, guest: 8900, host: 8900
    primary.vm.network :forwarded_port, guest: 9001, host: 9001
    primary.vm.network :forwarded_port, guest: 15670, host: 15670
    primary.vm.network :forwarded_port, guest: 15671, host: 15671
    primary.vm.network :forwarded_port, guest: 15672, host: 15672
    primary.vm.network :forwarded_port, guest: 61613, host: 61613
    primary.vm.network :private_network, ip: "192.168.50.4"
    primary.vm.provision "chef_solo" do |chef|
      chef.add_recipe "rabbitmq::default"
      chef.add_recipe "rabbitmq::mgmt_console"
      chef.add_recipe "rabbitmq::plugin_management"
      chef.add_recipe "supervisor::default"
      chef.add_recipe "zeromq::default"
      chef.add_recipe "rabbitmq-in-depth::default"
      chef.add_recipe "rabbitmq-in-depth::gitrepo"
      chef.add_recipe "rabbitmq-in-depth::ipython"
      chef.add_recipe "rabbitmq-in-depth::opencv"
      chef.add_recipe "rabbitmq-in-depth::rabbitmq"
      chef.add_recipe "rabbitmq-in-depth::statelessd"
      chef.json = {
        :erlang => {
          :gui_tools => false,
          :install_method => "package"
        },
        :rabbitmq => {
          :use_distro_version => false,
          :version => rabbitmq_version,
          :enable_plugins => %w[rabbitmq_management_visualiser
                                rabbitmq_consistent_hash_exchange
                                rabbitmq_federation
                                rabbitmq_federation_management
                                rabbitmq_mqtt
                                rabbitmq_shovel
                                rabbitmq_shovel_management
                                rabbitmq_stomp
                                rabbitmq_tracing
                                rabbitmq_web_stomp
                                rabbitmq_web_stomp_examples]
        },
        :supervisor => {
          :inet_port => 9001
        },
        :zeromq => {
          :src_version => "4.0.1",
          :src_mirror => "http://download.zeromq.org/zeromq-4.0.1.tar.gz"
        }
      }
    end
  end

  config.vm.define "secondary" do |secondary|
    secondary.vm.hostname = 'secondary'
    secondary.vm.network :forwarded_port, guest: 5672, host: 5673
    secondary.vm.network :private_network, ip: "192.168.50.5"
    secondary.vm.provision "chef_solo" do |secondary_chef|
      secondary_chef.add_recipe "rabbitmq::default"
      secondary_chef.add_recipe "rabbitmq::plugin_management"
      secondary_chef.add_recipe "rabbitmq-in-depth::default"
      secondary_chef.add_recipe "rabbitmq-in-depth::rabbitmq"
      secondary_chef.json = {
        :erlang => {
          :gui_tools => false,
          :install_method => "package"
        },
        :rabbitmq => {
          :use_distro_version => false,
          :version => rabbitmq_version,
          :enable_plugins => %w[rabbitmq_management_agent
                                rabbitmq_consistent_hash_exchange]
        }
      }
    end
  end
end
